#include "common/include.h"

#include "cmd_line/src/command_line_parser.cpp"
#include "timer/src/clock.cpp"
#include "thread/src/thread_base.cpp"
#include "thread/src/monitor_thread.cpp"
#include "spdlog_wrapper/src/logger_create_info.cpp"
#include "spdlog_wrapper/src/everest_spdlog.cpp"
#include "control_monitor/src/thread_monitor.cpp"
#include "control_monitor/src/control_monitor.cpp"